### ISSUE TITLE
Missing PackageKit::Transaction::message signal

### ISSUE THREAD

**Issue by aleixpol** [hughsie/PackageKit-Qt#10]
I'm getting this error message. Has it disappeared from the PackageKit spec?

```
QObject::connect: No such signal OrgFreedesktopPackageKitTransactionInterface::Message(uint,QString) in /home/apol/devel/frameworks/PackageKit-Qt/src/transaction.cpp:120
```

**Comment by ximion** [comment]
Yes, this has been gone for ages: https://github.com/hughsie/PackageKit/commit/ca03260c45ffd490cb8f9561d13024e5d0102679

**Comment by dantti** [comment]
to close this one I guess we should bump the so version and remove it, right?

**Comment by aleixpol** [comment]
We can't remove it and maintain ABI. We can add Q_DECL_DEPRECATED though.

**Comment by dantti** [comment]
which is why I said to bump the so version

**Comment by dantti** [comment]
Also it seems it's already marked

**Comment by aleixpol** [comment]
Let's just close the issue
