### ISSUE TITLE
PackageKitQt doesn't compile

### ISSUE THREAD

**Issue by aleixpol** [hughsie/PackageKit-Qt#12]
Possibly for changes in PackageKit

```
FAILED: src/daemonproxy.cpp src/daemonproxy.h 
cd /home/apol/build-devel/frameworks/PackageKit-Qt/src && /home/apol/devel/kde5/bin/qdbusxml2cpp -N -m -p daemonproxy /usr/share/dbus-1/interfaces/org.freedesktop.PackageKit.xml
Got unknown type `a{sv}'
You should add <annotation name="org.qtproject.QtDBus.QtTypeName" value="<type>"/> to the XML description
```

**Comment by ximion** [comment]
This is actually a bug in PK itself, it needs a proper annotation for Qt.
And also, QPK finally needs a release...
I will discuss this with @hughsie and @dantti - personally, I wouldn's see it as a bad idea to move QPK to KDE infrastructure, or at least make it possible for me or dantti to do proper releases on Freedesktop (for that, one needs to be in the PK group on annarchy.fd.o).

**Comment by aleixpol** [comment]
Hi,
I looked into it a bit closer, as I needed to build it and just realized that it's been fixed in PackageKit for a while:
```
commit a2f8be68442529ab7c9883d55631bcfb6395b86d
Author: Dominique Leuenberger <dimstar@opensuse.org>
Date:   Fri Jul 15 13:17:57 2016 +0200

    Annotate PreparedUpgrade DBus property for usage in PackageKit-Qt
```

So I guess it's mostly about releasing a new version of PackageKit with the fix. Would that be possible, @hughsie? It doesn't seem to be in 1.1.3

**Comment by hughsie** [comment]
Sure, I can do a release next week if that works.
