### ISSUE TITLE
_IMPORT_PREFIX not set(?)

### ISSUE THREAD

**Issue by sl1pkn07** [hughsie/PackageKit-Qt#2]
~~~
PackageKit-Qt Qt5 port don't set _IMPORT_PREFIX variable

CMake Error in applets/kicker/CMakeLists.txt:
  Imported target "PK::packagekitqt5" includes non-existent path

```
"/include/packagekitqt5/PackageKit/"
```

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
- The path was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and references files it does not
  provide.
~~~

greetings

**Comment by aleixpol** [comment]
That's because CMAKE_INSTALL_INCLUDEDIR is /include, can you make sure your CMakeCache.txt is correctly set?

**Comment by sl1pkn07** [comment]
//C header files (include)
CMAKE_INSTALL_INCLUDEDIR:PATH=include

full cmakecache: http://sl1pkn07.wtf/paste/view/27642be2

the install log http://sl1pkn07.wtf/paste/view/844c2d77

build with

    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib \
    -DUSE_QT5=ON
