### ISSUE TITLE
source verification

### ISSUE THREAD

**Issue by eworm-de** [hughsie/PackageKit-Qt#24]
Now that source tarballs are suppose to be downloaded from github... Any chance to upload file signatures at least? Would be nice if packagers could verify file integrity. Thanks!

**Comment by dantti** [comment]
Well it's a tag from the source, GitHub created the tarball, I don't know a way to upload a signature to it

**Comment by dantti** [comment]
ok found this https://wiki.debian.org/Creating%20signed%20GitHub%20releases
will try to do it.

**Comment by dantti** [comment]
done please test

**Comment by eworm-de** [comment]
Works perfectly. Thanks a lot!
Just pushed a package to Arch Linux staging repository.
