### ISSUE TITLE
Include path in pkg-config file wrong?

### ISSUE THREAD

**Issue by Thaodan** [hughsie/PackageKit-Qt#26]
Hey,

I'm tring to add this lib via pkgconfig in a [qmake](https://github.com/Thaodan/ornplugin/blob/pkgconfig_link/ornplugin.pro#L9) file.

But the include path returned is wrong I think, "@prefix@/include/packagekitqt5/PackageKit" is returned
instead "@prefix@/include/packagekitqt5".
Is this indented?

**Comment by ximion** [comment]
From how QPK is used in projects building with CMake, this is definitely unintended.

**Comment by Thaodan** [comment]
@Kaffeine on #jollafanclub suggested to add a compatiblity path for those that did a workaround on the issue before the fix eg. add the old path too until 1.1.
