### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by AcarBurak** [hughsie/PackageKit-Qt#3]
Sorry for the noob issue, but what should I do? (On Debian Jessie)

:-1: error: No rule to make target '/home/burak/bin/PackageKit-Qt/src/PK_INTERFACES_DIR-NOTFOUND/org.freedesktop.PackageKit.Transaction.xml', needed by 'src/transactionproxy.cpp'.  Stop.

**Comment by ximion** [comment]
Did you install PackageKit? (see https://github.com/hughsie/PackageKit )
I'll maybe add a better check for the presence of the DBus interfaces...

**Comment by AcarBurak** [comment]
That's turned out to be noober than I've thought; sorry forgot that I should have installed it first.

But now seemingly having compiled and installed it I can't find any executable like synaptic; that is, I was waiting for a package manager like synaptic or muon. Is it not?

This is what terminal has produced:

burak@debian:~/bin/PackageKit-Qt-build$ make
[ 14%] Built target mocs
[100%] Built target packagekitqt5
burak@debian:~/bin/PackageKit-Qt-build$ sudo make install
[sudo] password for burak: 
[ 14%] Built target mocs
[100%] Built target packagekitqt5
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/lib/cmake/packagekitqt5/PackageKitQtTargets.cmake
-- Installing: /usr/lib/cmake/packagekitqt5/PackageKitQtTargets-debug.cmake
-- Installing: /usr/lib/libpackagekitqt5.so.0.9.6
-- Installing: /usr/lib/libpackagekitqt5.so.0
-- Installing: /usr/lib/libpackagekitqt5.so
-- Installing: /usr/lib/pkgconfig/packagekitqt5.pc
-- Installing: /usr/include/packagekitqt5/PackageKit/Daemon
-- Installing: /usr/include/packagekitqt5/PackageKit/Transaction
-- Installing: /usr/include/packagekitqt5/PackageKit/common.h
-- Installing: /usr/include/packagekitqt5/PackageKit/daemon.h
-- Installing: /usr/include/packagekitqt5/PackageKit/transaction.h
-- Installing: /usr/include/packagekitqt5/PackageKit/Details
-- Installing: /usr/include/packagekitqt5/PackageKit/details.h
-- Installing: /usr/include/packagekitqt5/PackageKit/bitfield.h
-- Installing: /usr/lib/cmake/packagekitqt5/packagekitqt5-config.cmake
-- Installing: /usr/lib/cmake/packagekitqt5/packagekitqt5-config-version.cmake

**Comment by ximion** [comment]
Ah, no :D QPK is a library which enables developers to build package-managers. If you're looking for a package-manager, try Apper: http://quickgit.kde.org/index.php?p=apper.git
or Muon, which just recently added a PK backend: http://quickgit.kde.org/?p=muon.git

**Comment by AcarBurak** [comment]
All right, sorry for noise. I was trying to be KDE-free (as well as GTK-free)!

**Comment by ximion** [comment]
Then you need to create a new package-manager GUI based on packagekit-qt ;-)

**Comment by AcarBurak** [comment]
Well... !! At least I'm ready to install one if anybody makes it!

**Comment by dantti** [comment]
Actually Apper 2 (yet to be developed) will probably not depend on any KDE
libraries...
but I dunno when I'll write it :P

2015-02-13 11:24 GMT-02:00 AcarBurak <notifications@github.com>:

> Well... !! At least I'm ready to install one if anybody makes it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hughsie/PackageKit-Qt/issues/3#issuecomment-74252643>.
>



-- 
Daniel Nicoletti

KDE Developer - http://dantti.wordpress.com

**Comment by AcarBurak** [comment]
Glad to hear that.

**Comment by ranveeraggarwal** [comment]
Hi! I have a noob doubt too. I am not very familiar with cmake, and I'm using packagekit-qt for a project. More specifically, I need to compile it using `qt5`. But when I do a cmake, it uses Qt4 libs by default. How do I make it use qt5?

**Comment by ximion** [comment]
Ehm... Run cmake with ```-DUSE_QT5=ON```? ;-)
